name = "DistMesh2D"
uuid = "f35b52f9-dac7-460d-8eba-9271352c98c8"
authors = ["jstarczewski <jan.a.starczewski@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Deldir = "64db5801-a3ae-51a7-b7d2-a0a5f0813e47"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
GeometricalPredicates = "â‰¥ 0.2.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
